name: torch-ngp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - cudatoolkit=11.3
  - ninja
  - trimesh
  - opencv
  - tensorboardX
  - pytorch=1.8
  - numpy 
  - pandas
  - tqdm
  - matplotlib
  - rich
  - packaging
  - scipy
  - imageio
  - lpips
  - torch-ema
  - pip:
    - PyMCubes
    - pysdf
    - dearpygui
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
